name: "Read the refs/branches to use for checking out upstream repos"
description: "Reads and outputs the refs/branches from PR description to use for checking out upstream repos."
author: "wpsocio"

outputs:
  random-number:
    description: "Refs JSON"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Get details
      uses: actions/github-script@v7
      id: details
      with:
        script: |
          // Get the PR description
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });


          console.log('body is:', pr.body);

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash
