name: "Read the refs/branches to use for checking out upstream repos"
description: "Reads and outputs the refs/branches from PR description to use for checking out upstream repos."
author: "wpsocio"

outputs:
  result:
    description: "Refs JSON"
    value: ${{ steps.details.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Get details
      uses: actions/github-script@v7
      id: details
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });

          const refsCommentRegex =
            /<!--- REMOTE REFS START -->(?<content>.+)<!--- REMOTE REFS END -->/is;

          const result = (pr.body || '').match(refsCommentRegex);

          console.log('result:', result);

          if (!result?.groups?.content) {
            return { refs: [] };
          }

          const refs = result.groups.content
            .trim()
            .split(/[\n\r]+/)
            .map((line) => {
              const [name, ref] = line.split(/:\s?/);
              return { name, ref };
            });

          console.log('refs:', refs);

          return { refs };
