name: Prepare or publish release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare or publish release
    if: github.repository == 'wpsocio/wp-projects'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_IR }}

      - name: Setup Environment
        uses: ./actions/setup
        with:
          enable-wireit-cache: true

      - name: Setup PHP
        run: "pnpm run setup:php"

      - name: Setup git user
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME_IR }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL_IR }}"

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm prep-release
          title: Prepare for next release
          commit: Prepare for next release
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_IR }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_IR }}
