name: Prepare or publish release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare or publish release
    if: github.repository == 'wpsocio/wp-projects'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./actions/setup
        with:
          lockfile: pnpm-hashed.lock
          enable-wireit-cache: true

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm release
          version: pnpm prep-release
          title: Prepare for next release
          commit: Prepare for next release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
